name: ewallet_hackathon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_screenutil: ^5.0.0+2
  foldable_sidebar: ^1.0.0
  http: ^0.13.3
  alan_voice: ^2.3.0
  razorpay_flutter: ^1.2.6
  fluttertoast: ^8.0.7
  responsive_builder: ^0.4.1
  shared_preferences: ^2.0.6
  progress_hud: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/account.png
    - asset/images/avatar1.png
    - asset/images/avatar2.png
    - asset/images/avatar3.png
    - asset/images/avatar4.png
    - asset/images/cloud.png
    - asset/images/electricity.png
    - asset/images/flight.png
    - asset/images/logo.png
    - asset/images/menu.png
    - asset/images/more.png
    - asset/images/movie.png
    - asset/images/phone.png
    - asset/images/receiveMoney.png
    - asset/images/report.png
    - asset/images/scanqr.png
    - asset/images/sendMoney.png
    - asset/images/sideImg.png
    - asset/images/tag.png
    - asset/images/calender.png
    - asset/images/card_cvv.png
    - asset/images/visa.png
    - asset/images/jcb.png
    - asset/images/verve.png
    - asset/images/discover.png
    - asset/images/american_express.png
    - asset/images/dinners_club.png
    - asset/images/mastercard.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: avenir
      fonts:
        - asset: asset/font/avenirMedium.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: ubuntu
      fonts:
        - asset: asset/font/Ubuntu-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
